# Site settings
title: L.hyun blog
tagline: 디지털 마케팅과 광고에 대한 소소한 생각
description: "광고와 디지털 마케팅 내용을 다룹니다."
url: "https://hisnen.com"
author:
  name: "Lhyun"
  email: "hisnen@naver.com"
  url: "https://hisnen.com"

# 블로그 disqus shortname
disqus:
  shortname: www-hisnen-com

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
